#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongBanHang
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
    using System.Diagnostics;

    [global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TestBanHang")]
	public partial class DataAccessDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertProduct(Product instance);
    partial void UpdateProduct(Product instance);
    partial void DeleteProduct(Product instance);
    partial void InsertReceipt(Receipt instance);
    partial void UpdateReceipt(Receipt instance);
    partial void DeleteReceipt(Receipt instance);
    partial void InsertReceiptDetail(ReceiptDetail instance);
    partial void UpdateReceiptDetail(ReceiptDetail instance);
    partial void DeleteReceiptDetail(ReceiptDetail instance);
    #endregion
		
		public DataAccessDataContext() : 
				base(global::HeThongBanHang.Properties.Settings.Default.TestBanHangConnectionString, mappingSource)
		{
            Debug.WriteLine(HeThongBanHang.Properties.Settings.Default.TestBanHangConnectionString);

            OnCreated();
		}
		
		public DataAccessDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataAccessDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataAccessDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataAccessDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Product> Products
		{
			get
			{
				return this.GetTable<Product>();
			}
		}
		
		public System.Data.Linq.Table<Receipt> Receipts
		{
			get
			{
				return this.GetTable<Receipt>();
			}
		}
		
		public System.Data.Linq.Table<ReceiptDetail> ReceiptDetails
		{
			get
			{
				return this.GetTable<ReceiptDetail>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.rp_print")]
		public ISingleResult<rp_printResult> rp_print([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> receipid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), receipid);
			return ((ISingleResult<rp_printResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Product")]
	public partial class Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _Code;
		
		private string _Name;
		
		private System.Nullable<long> _Price;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnPriceChanging(System.Nullable<long> value);
    partial void OnPriceChanged();
    #endregion
		
		public Product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NChar(1000)")]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NChar(1000)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="BigInt")]
		public System.Nullable<long> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Receipt")]
	public partial class Receipt : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _SellerName;
		
		private string _SellerAddress;
		
		private string _SellerPhone;
		
		private string _BuyerName;
		
		private string _BuyerAddress;
		
		private string _BuyerPhone;
		
		private string _TotalMoneyReceipt;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnSellerNameChanging(string value);
    partial void OnSellerNameChanged();
    partial void OnSellerAddressChanging(string value);
    partial void OnSellerAddressChanged();
    partial void OnSellerPhoneChanging(string value);
    partial void OnSellerPhoneChanged();
    partial void OnBuyerNameChanging(string value);
    partial void OnBuyerNameChanged();
    partial void OnBuyerAddressChanging(string value);
    partial void OnBuyerAddressChanged();
    partial void OnBuyerPhoneChanging(string value);
    partial void OnBuyerPhoneChanged();
    partial void OnTotalMoneyReceiptChanging(string value);
    partial void OnTotalMoneyReceiptChanged();
    #endregion
		
		public Receipt()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SellerName", DbType="NVarChar(1000)")]
		public string SellerName
		{
			get
			{
				return this._SellerName;
			}
			set
			{
				if ((this._SellerName != value))
				{
					this.OnSellerNameChanging(value);
					this.SendPropertyChanging();
					this._SellerName = value;
					this.SendPropertyChanged("SellerName");
					this.OnSellerNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SellerAddress", DbType="NVarChar(1000)")]
		public string SellerAddress
		{
			get
			{
				return this._SellerAddress;
			}
			set
			{
				if ((this._SellerAddress != value))
				{
					this.OnSellerAddressChanging(value);
					this.SendPropertyChanging();
					this._SellerAddress = value;
					this.SendPropertyChanged("SellerAddress");
					this.OnSellerAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SellerPhone", DbType="NVarChar(1000)")]
		public string SellerPhone
		{
			get
			{
				return this._SellerPhone;
			}
			set
			{
				if ((this._SellerPhone != value))
				{
					this.OnSellerPhoneChanging(value);
					this.SendPropertyChanging();
					this._SellerPhone = value;
					this.SendPropertyChanged("SellerPhone");
					this.OnSellerPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuyerName", DbType="NVarChar(1000)")]
		public string BuyerName
		{
			get
			{
				return this._BuyerName;
			}
			set
			{
				if ((this._BuyerName != value))
				{
					this.OnBuyerNameChanging(value);
					this.SendPropertyChanging();
					this._BuyerName = value;
					this.SendPropertyChanged("BuyerName");
					this.OnBuyerNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuyerAddress", DbType="NVarChar(1000)")]
		public string BuyerAddress
		{
			get
			{
				return this._BuyerAddress;
			}
			set
			{
				if ((this._BuyerAddress != value))
				{
					this.OnBuyerAddressChanging(value);
					this.SendPropertyChanging();
					this._BuyerAddress = value;
					this.SendPropertyChanged("BuyerAddress");
					this.OnBuyerAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuyerPhone", DbType="NVarChar(1000)")]
		public string BuyerPhone
		{
			get
			{
				return this._BuyerPhone;
			}
			set
			{
				if ((this._BuyerPhone != value))
				{
					this.OnBuyerPhoneChanging(value);
					this.SendPropertyChanging();
					this._BuyerPhone = value;
					this.SendPropertyChanged("BuyerPhone");
					this.OnBuyerPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalMoneyReceipt", DbType="NVarChar(1000)")]
		public string TotalMoneyReceipt
		{
			get
			{
				return this._TotalMoneyReceipt;
			}
			set
			{
				if ((this._TotalMoneyReceipt != value))
				{
					this.OnTotalMoneyReceiptChanging(value);
					this.SendPropertyChanging();
					this._TotalMoneyReceipt = value;
					this.SendPropertyChanged("TotalMoneyReceipt");
					this.OnTotalMoneyReceiptChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ReceiptDetail")]
	public partial class ReceiptDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private long _ReportId;
		
		private string _Name;
		
		private System.Nullable<long> _Price;
		
		private System.Nullable<long> _Quantity;
		
		private System.Nullable<long> _TotalMoneyDetail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnReportIdChanging(long value);
    partial void OnReportIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnPriceChanging(System.Nullable<long> value);
    partial void OnPriceChanged();
    partial void OnQuantityChanging(System.Nullable<long> value);
    partial void OnQuantityChanged();
    partial void OnTotalMoneyDetailChanging(System.Nullable<long> value);
    partial void OnTotalMoneyDetailChanged();
    #endregion
		
		public ReceiptDetail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportId", DbType="BigInt NOT NULL")]
		public long ReportId
		{
			get
			{
				return this._ReportId;
			}
			set
			{
				if ((this._ReportId != value))
				{
					this.OnReportIdChanging(value);
					this.SendPropertyChanging();
					this._ReportId = value;
					this.SendPropertyChanged("ReportId");
					this.OnReportIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(1000)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="BigInt")]
		public System.Nullable<long> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="BigInt")]
		public System.Nullable<long> Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this.OnQuantityChanging(value);
					this.SendPropertyChanging();
					this._Quantity = value;
					this.SendPropertyChanged("Quantity");
					this.OnQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalMoneyDetail", DbType="BigInt")]
		public System.Nullable<long> TotalMoneyDetail
		{
			get
			{
				return this._TotalMoneyDetail;
			}
			set
			{
				if ((this._TotalMoneyDetail != value))
				{
					this.OnTotalMoneyDetailChanging(value);
					this.SendPropertyChanging();
					this._TotalMoneyDetail = value;
					this.SendPropertyChanged("TotalMoneyDetail");
					this.OnTotalMoneyDetailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class rp_printResult
	{
		
		private long _Id;
		
		private string _SellerName;
		
		private string _SellerAddress;
		
		private string _SellerPhone;
		
		private string _BuyerName;
		
		private string _BuyerAddress;
		
		private string _BuyerPhone;
		
		private string _TotalMoneyReceipt;
		
		private long _Id1;
		
		private long _ReportId;
		
		private string _Name;
		
		private System.Nullable<long> _Price;
		
		private System.Nullable<long> _Quantity;
		
		private System.Nullable<long> _TotalMoneyDetail;
		
		public rp_printResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SellerName", DbType="NVarChar(1000)")]
		public string SellerName
		{
			get
			{
				return this._SellerName;
			}
			set
			{
				if ((this._SellerName != value))
				{
					this._SellerName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SellerAddress", DbType="NVarChar(1000)")]
		public string SellerAddress
		{
			get
			{
				return this._SellerAddress;
			}
			set
			{
				if ((this._SellerAddress != value))
				{
					this._SellerAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SellerPhone", DbType="NVarChar(1000)")]
		public string SellerPhone
		{
			get
			{
				return this._SellerPhone;
			}
			set
			{
				if ((this._SellerPhone != value))
				{
					this._SellerPhone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuyerName", DbType="NVarChar(1000)")]
		public string BuyerName
		{
			get
			{
				return this._BuyerName;
			}
			set
			{
				if ((this._BuyerName != value))
				{
					this._BuyerName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuyerAddress", DbType="NVarChar(1000)")]
		public string BuyerAddress
		{
			get
			{
				return this._BuyerAddress;
			}
			set
			{
				if ((this._BuyerAddress != value))
				{
					this._BuyerAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuyerPhone", DbType="NVarChar(1000)")]
		public string BuyerPhone
		{
			get
			{
				return this._BuyerPhone;
			}
			set
			{
				if ((this._BuyerPhone != value))
				{
					this._BuyerPhone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalMoneyReceipt", DbType="NVarChar(1000)")]
		public string TotalMoneyReceipt
		{
			get
			{
				return this._TotalMoneyReceipt;
			}
			set
			{
				if ((this._TotalMoneyReceipt != value))
				{
					this._TotalMoneyReceipt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id1", DbType="BigInt NOT NULL")]
		public long Id1
		{
			get
			{
				return this._Id1;
			}
			set
			{
				if ((this._Id1 != value))
				{
					this._Id1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportId", DbType="BigInt NOT NULL")]
		public long ReportId
		{
			get
			{
				return this._ReportId;
			}
			set
			{
				if ((this._ReportId != value))
				{
					this._ReportId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(1000)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="BigInt")]
		public System.Nullable<long> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="BigInt")]
		public System.Nullable<long> Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this._Quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalMoneyDetail", DbType="BigInt")]
		public System.Nullable<long> TotalMoneyDetail
		{
			get
			{
				return this._TotalMoneyDetail;
			}
			set
			{
				if ((this._TotalMoneyDetail != value))
				{
					this._TotalMoneyDetail = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
